name: Changed files
description: Get list of changed files between two branches

inputs:
  base-branch:
    description: Base branch (destination of a pull request)
    required: true
    default: ${{ github.base_ref }}
  head-branch:
    description: Head branch (source of a pull request)
    required: false
    default: ${{ github.head_ref }}

outputs:
  changed-files:
    description: List of changed files
    value: ${{ steps.changed-files.outputs.all_changed_files }}

runs:
  using: composite
  steps:
    - name: Get changed files
      id: changed-files
      shell: bash
      run: |
        BASE_BRANCH=${{ inputs.base-branch }}
        HEAD_BRANCH=${{ inputs.head-branch }}
        BASE_REPO_URL=${{ github.event.pull_request.base.repo.html_url }}

        # Add remote to head in case it's a fork
        HEAD_REPO_URL=${{ github.event.pull_request.head.repo.html_url }}
        git remote add head $HEAD_REPO_URL

        git fetch origin $BASE_BRANCH --depth 1
        git fetch head $HEAD_BRANCH --depth 1
        CHANGED_FILES=$(git diff --name-only origin/$BASE_BRANCH head/$HEAD_BRANCH)
        {
          echo 'all_changed_files<<EOF'
          echo "${CHANGED_FILES}"
          echo EOF
        } >> $GITHUB_OUTPUT
