name: Changed files
description: Get list of changed files between two git refs.

inputs:
  base-ref:
    description: Base branch (destination of a pull request). Defaults to the base branch of the pull request.
    required: false
    default: ${{ github.base_ref }}
  head-ref:
    description: Head branch (source of a pull request). Defaults to the ref of the pull request.
    required: false
    default: ${{ github.ref }}

outputs:
  changed-files:
    description: List of changed files
    value: ${{ steps.changed-files.outputs.all_changed_files }}

runs:
  using: composite
  steps:
    - name: Get changed files
      id: changed-files
      shell: bash
      run: |
        git fetch origin ${{ inputs.base-ref }}:refs/heads/changed_base --depth 1
        git fetch origin ${{ inputs.head-ref }}:refs/heads/changed_head --depth 1

        cat <<END_OUTPUT >> $GITHUB_OUTPUT
        all_changed_files<<EOF
        $( git diff --name-only refs/heads/changed_base refs/heads/changed_head )
        EOF
        END_OUTPUT
