repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files

# static analysis tool for GitHub Actions
- repo: https://github.com/zizmorcore/zizmor-pre-commit
  rev: 0703f40666c15722d5402120b1bbd61bc3503772  # frozen: v1.24.0
  hooks:
  - id: zizmor
    args:
    - --fix
