name: Close a snap channel
description: |
  This action closes the snap channel provided.

inputs:
  name:
    description: |
      The name of the snap to close the channel for. Defaults to the repository name.
  channel:
    required: true
    description: |
      The snap channel to close.
  snapcraft-token:
    required: true
    description: |
      The token obtained with `snapcraft export-login --acls package_access,package_push,package_release -`.
  snapcraft-channel:
    required: true
    description: |
      The channel to install Snapcraft from. Defaults to `stable`.
    default: stable

runs:
  using: composite
  steps:
  - shell: bash
    env:
      SNAPCRAFT_CHANNEL: ${{ inputs.snapcraft-channel }}
    run: |
      sudo snap install snapcraft --classic --channel ${SNAPCRAFT_CHANNEL}

  - id: get-name
    shell: bash
    if: ${{ ! inputs.name }}
    run: |
      echo "name=${GITHUB_REPOSITORY#*/}" >> "$GITHUB_OUTPUT"

  - shell: bash
    env:
      SNAPCRAFT_STORE_CREDENTIALS: ${{ inputs.snapcraft-token }}
      CHANNEL: ${{ inputs.channel }}
      SNAP_NAME: ${{ inputs.name || steps.get-name.outputs.name }}
    run: |
      snapcraft close "$( echo "${SNAP_NAME}" | tr 'A-Z' 'a-z' )" "${CHANNEL}"
